### ISSUE TITLE
Imcompability with peasycam

### ISSUE THREAD

**Issue by cgiles** [cansik/processing-postfx#28]
Hi, as I tried to use postfx with peasycam : http://mrfeinberg.com/peasycam/ , I got this bug : 
![image](https://user-images.githubusercontent.com/404078/35850532-75aecfc4-0b25-11e8-9827-83021d7fa766.png)
As you can see, the original is displayed in the background, and the post fx render appears in the front, scaled down.

I tried to move the focus point of my peasycam object, but it doesn't fix the issue :/

a sketch which reproduce this bug : 
```
import ch.bildspur.postfx.builder.*;
import ch.bildspur.postfx.pass.*;
import ch.bildspur.postfx.*;

import peasy.*;
import peasy.org.apache.commons.math.*;
import peasy.org.apache.commons.math.geometry.*;

PeasyCam cam;

PostFX fx;
void setup(){
  size(400,400,P3D);
  cam=new PeasyCam(this, 800);
  fx = new PostFX(this);  
}
void draw(){
  background(100);
  pushMatrix();
translate(width/2,height/2);
rotateY(frameCount/17.0);
box(200);
    popMatrix();
 fx.render()
    .bloom(0.5, 20, 40)
    .compose();

}
```

regards

**Comment by cgiles** [comment]
I posted the issue here too : https://github.com/jdf/peasycam/issues/33

**Comment by cansik** [comment]
I have to tell you that this behaviour is not directly an issue. The PostFX library uses 2d textures to apply shaders, so `compose()` is drawing the output texture onto the screen. If you are using peasycam, which changes the view matrix, then you have to reset the matrix before drawing the effect texture.

With peasycam you can use `beginHUD()` and `endHUD()` to reset the view matrix:

```java
cam.beginHUD();
fx.render()
  .bloom(0.5, 20, 40)
  .compose();
cam.endHUD();
```

I have added your example to the examples:
[PeasyCamExample.pde](https://github.com/cansik/processing-postfx/blob/master/examples/PeasyCamExample/PeasyCamExample.pde)

**Comment by cgiles** [comment]
Great, thanks, it works 👍
