### ISSUE TITLE
Add more shaders to the library

### ISSUE THREAD

**Issue by cansik** [cansik/processing-postfx#3]
Add more default shaders to the library:

#### Color
* Brightness and Contrast Shader
* Invert Shader
* Grayscale Shader
* LUT Shader (*nice to have*)

#### Reconstruction
* Denoise Shader

#### Effects
* Bloom Shader
* Pixelate Shader by [prince_polka](https://forum.processing.org/two/discussion/comment/93670/#Comment_93670)
* Chromatic aberration shader
* Noise Shader
* Vignette Shader
* RGB Split Shader

**Comment by b2renger** [comment]
Hi this is a great idea for a library

I was wondering about blending shaders would be in the scope of this lib ?

Sometime ago I played with blending shaders and got a little processing app to experiment with different kind of blending : https://github.com/b2renger/Processing_Blends_Shaders

The code is not really good and I always thought I should find a way to refactor those.
 Your post-fx lib seems perfect for this job. Would you be open to me working on that ?

**Comment by cansik** [comment]
@b2renger Yep sounds like a good idea. I think some [blending shaders](https://processing.org/reference/blendMode_.html) are already implemented in processing:

```java
blendMode(BLEND);
```

But I will check out your blending shaders 👍

**Comment by cansik** [comment]
Ah ok, now I know what you mean with blending shaders :) Yeah I will check out your shaders.

**Comment by b2renger** [comment]
@cansik I was not aware of the blendMode() function, before I used blend().
I think blend() was computed on the cpu, It looks like blendMode still computes from arrays of pixels in java
https://github.com/processing/processing/commit/1ff98f928a31334a003cb567a6febae4736a4a31

maybe a faster implementation with shaders could be cool, let me know what you think.
(I didn't write those shader myself, sadly I'm not capable of doing so, yet :) )

**Comment by cansik** [comment]
@b2renger The code you were looking at is from 2012, this is the actual implementation of the `PGraphicsJava2D` class: [PGraphicsJava2D.java#L996-L1012](https://github.com/processing/processing/blob/3771a5283f681ff3126f6e3b4423cf1e4f8d512c/core/src/processing/awt/PGraphicsJava2D.java#L996-L1012)

It looks like the compositing mode is set of the underlaying `Graphic2D` object. But I could not find the `blendModeImpl()` method in the `PGraphics2D` and `PGraphics3D` classes.

But just because of my speed tests with this library, I think the blending is calculated on the **GPU**.

**Comment by b2renger** [comment]
@cansik , ok then maybe it's not usefull to bother with blends then.
Let me know what you decide, and If you think I can help I'd be glad to do so.

**Comment by cansik** [comment]
The problem is that we are using `P3D` and `P2D` textures and set the blend mode there. And I think because of that, it will be done with the compositing methods of OpenGL, but I will check that :)

How do you think, should the API look like for the blend modes with this library? Something like that:

```java
PGraphics texture1;
PGraphics texture2;

fx.render(texture1)
        .brightnessContrast(0.1f, 1.0f)
        .blend(BlendMode.SCREEN, texture2)
        .compose(passResult);
```

If we really implement it here :)

**Comment by b2renger** [comment]
Yes definitely something like that !

**Comment by cansik** [comment]
I've implemented now a lot of useful shaders (about 11). I think that's enough for the current version ;)
