### ISSUE TITLE
Would it be possible to make an HDR postfx filter?

### ISSUE THREAD

**Issue by quinton-ashley** [cansik/processing-postfx#31]
https://learnopengl.com/Advanced-Lighting/HDR

**Comment by cansik** [comment]
@quinton-ashley I will have a look

**Comment by quinton-ashley** [comment]
wow! That was fast.  Your code looks like it should work but when I tried it out it seems opengl is still rendering the frames in SDR RGB instead of 10 bit BT2020 colorspace YUV444.  Does something in the Processing core need to change or do you think this conversion could be done with a shader?

**Comment by cansik** [comment]
It's not finished yet :) I just added tone mapping and exposure. We need to allocate a new framebuffer with a larger float depth. But I will look into this :)

**Comment by quinton-ashley** [comment]
ah I gotcha, sounds good.  Thank you!

**Comment by quinton-ashley** [comment]
hey just checking in on you!  Have you made any more progress on this?  I'm excited if this is possible.  The new Windows 10 update now has really solid HDR/WCG support so that might make things easier for you.

**Comment by cansik** [comment]
@quinton-ashley Yeah I tried out some things, but it is not that easy to allocate this kind of buffer in processing :) Maybe I have time during the summer!

**Comment by quinton-ashley** [comment]
Sweet!
